### ISSUE TITLE
Issue 1

### ISSUE THREAD

**Issue by abhinavg916** [lok3ndrasingh/testrepo#5]
What is the purpose of this repo?

**Comment by lokendras12** [comment]
to test the functionalities and to create a backup of testing codes.

**Comment by abhinavg916** [comment]
What functionalities are we testing, please tell me!

**Comment by lokendras12** [comment]
regarding the navigation among different tabs in our application.

**Comment by abhinavg916** [comment]
Ok. I understood it.

**Comment by abhinavg916** [comment]
Let me try once more

**Comment by lokendras12** [comment]
ok

**Comment by abhinavg916** [comment]
Thanks
